### PR TITLE
make discord bot use countDocuments()

### PR DESCRIPTION
**Pull request by vkarpov15**

### CODE REVIEW

**Review by jeffreyscarpenter — APPROVED** [review]
this will have the 1000 document max count limitation, is that ok?

**Comment by vkarpov15** [comment]
@jeffreyscarpenter would there still be the 1000 limit if we used `find()`?

**Comment by jeffreyscarpenter** [comment]
> @jeffreyscarpenter would there still be the 1000 limit if we used `find()`?

IDK, @tatu-at-datastax what would you recommend here?

**Comment by vkarpov15** [comment]
I took a quick look and it looks like `find()` isn't subject to the 1000 limit, the following script shows `find()` returns 1005 docs:

```javascript
const connect = require('./connect');
const mongoose = require('./mongoose');
const collectionName = 'emails';

const Email = mongoose.model('Email', mongoose.Schema({
  title: String
}), collectionName);

run().catch(error => {
  console.log(error);
  process.exit(-1);
});

async function run() {
  await connect();

  await Email.createCollection();
  for (let i = 0; i < 1005; ++i) {
    console.log(`${i} / 1005`);
    await Email.create({ title: `email ${i}` });
  }

  // Prints "Done 1000 1005"
  console.log('Done', await Email.countDocuments(), await Email.find().then(res => res.length));
}

```

So I'll just stick with `find()` and remove the `countDocuments()` comment.

**Pull request merged**
